language: rust
rust:
  - stable
  - beta
  - nightly
sudo: required
dist: trusty
#cache: cargo
branches:
  only:
    - master
# Needed for codecov reporting
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - libssl-dev
env: RUST_BACKTRACE=full
before_script:
  - cargo install --force cargo-audit
  - cargo install --force cargo-when
script:
  - cargo test -- --test-threads=1
  - cargo test --doc
  - cargo test --example google
  # On nightly, test both the default config and special nightly features
  - cargo when --channel=nightly test --features nightly -- --test-threads=1
  - cargo when --channel=nightly build --all-features
  - cargo build --features futures-01,futures-03
  - cargo when -v ^1.39 -- build --features futures-03 --no-default-features
  - cargo build --features futures-01 --no-default-features
  - cargo audit
after_success: |
  RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin &&
  cargo tarpaulin --out Xml &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
notifications:
  email:
    on_success: never
