[package]
name = "openidconnect"
version = "1.0.0-alpha.9"
authors = ["David A. Ramos <ramos@cs.stanford.edu>"]
description = "OpenID Connect library"
license = "MIT"
repository = "https://github.com/ramosbugs/openidconnect-rs"
edition = "2018"

[features]
curl = ["oauth2/curl"]
reqwest = ["oauth2/reqwest"]
futures-01 = ["oauth2/futures-01", "futures-0-1"]
futures-03 = ["oauth2/futures-03", "futures-0-3"]
default = ["reqwest", "futures-03"]
nightly = []

[dependencies]
base64 = "0.9"
chrono = "0.4"
failure = "0.1"
failure_derive = "0.1"
futures-0-1 = { version = "0.1", optional = true, package = "futures" }
futures-0-3 = { version = "0.3", optional = true, package = "futures" }
http = "0.1"
itertools = "0.7.8"
log = "0.4"
oauth2 = "=3.0.0-alpha.6"
rand = "0.6"
retry = "0.5"
ring = "0.14"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
untrusted = "0.6"
url = "2.1"

[dev-dependencies]
color-backtrace = { version = "0.2" }
env_logger = "0.5"
hyper = "0.11"
pretty_assertions = "0.5"
reqwest_ = { package = "reqwest", version = "0.9" }
async-std = { version = "1.2.0", features = ["attributes"] }
